sudo: required
services:
  - docker

before_install:
  - docker build -t petergrossmann83/docker-react -f Dokcerfile.dev .

script:
  - docker run petergrossmann83/docker-react npm run test -- --coverage